version: '3'

services:
  anime-1:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-1"
    ports:
      - "18081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
  anime-2:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-2"
    ports:
      - "18082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
  anime-3:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-3"
    ports:
      - "18083:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
  mongodb:
    image: mongo:6.0.1
    container_name: 'anime-mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root       # this is sample value
      MONGO_INITDB_ROOT_PASSWORD: root       # this is sample value
    volumes:
      - ~/mongo-data:/data/db
