version: '3'

services:
  anime-1:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-1"
    ports:
      - "18081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
  anime-2:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-2"
    ports:
      - "18082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
  anime-3:
    image: ghcr.io/giggle-projects/anime-kr:latest
    container_name: "anime-3"
    ports:
      - "18083:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Seoul
