version: '3'
services:
  anime-kr-gateway:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/route-api.conf:/etc/nginx/conf.d/route-api.conf
    ports:
      - "11013:80"       # for api
    extra_hosts:
      - "host.docker.internal:host-gateway"