version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/route-api.conf:/etc/nginx/conf.d/route-api.conf
      - ./config/route-files.conf:/etc/nginx/conf.d/route-files.conf
      - ./config/route-monitoring.conf:/etc/nginx/conf.d/route-monitoring.conf
    ports:
      - "11013:80"       # for api
    extra_hosts:
      - "host.docker.internal:host-gateway"