version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: 'mysql'
    ports:
      - 3806:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/mysql-1.cnf:/etc/mysql/conf.d/my.cnf