version: '3'
services:
  anime-kr-gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/anime-kr.ecsimsw.com:/etc/letsencrypt/live/anime-kr.ecsimsw.com
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"