apiVersion: v1
kind: Service
metadata:
  labels:
    app: animekr-api
  name: animekr-svc
  namespace: animekr
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: animekr-api