name: deploy-prod
on:
  push:
    branches: [ main ]
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:
          port: 22
          script: |
            cd anime-kr
            git pull origin main
            cd api-server
            ./gradlew build -x test
            cd ..
            docker build -t ghcr.io/giggle-projects/anime-kr:0.0.1 -f api-server/Dockerfile .
            docker tag ghcr.io/giggle-projects/anime-kr:0.0.1 ghcr.io/giggle-projects/anime-kr:latest
            docker push ghcr.io/giggle-projects/anime-kr:latest
            sleep 3
            cd infra-service
            ./deploy.sh