name: deployment
on:
#  pull_request:
#    branches:
#      - release
#    types: [closed]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: release
          token: ${{ secrets.GHCR_ACCESS_TOKEN }}
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ecsimsw
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
          logout: true
      - name: Test application
        run: |
          cd application-server
          ./gradlew test
          cd ..
          echo ${{ inputs.working_directory }}
      - name: Checkout private vault code
        uses: actions/checkout@v4
        with:
          repository: Giggle-projects/anime-kr-vault
          ref: main
          token: ${{ secrets.GHCR_ACCESS_TOKEN }}
          run: |
            echo ${{ inputs.working_directory }}
            cp application-prod.properties application-server/src/main/resources/application-prod.properties
      - name: Build container image and push it to GHCR
        run: |
          cd application-server
          ./gradlew build -x test
          cd ..
          docker build -t ghcr.io/giggle-projects/anime-kr:latest -f application-server/dockerfile/Dockerfile .
          docker build -t ghcr.io/giggle-projects/anime-kr:backup -f application-server/dockerfile/DockerfileBackup .
          docker push ghcr.io/giggle-projects/anime-kr:latest
          docker push ghcr.io/giggle-projects/anime-kr:backup
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:
          port: 2023
          script: |
            cd ~/dev/anime-kr
            git pull
            cd infra-services
            ./deploy.sh
  deploy-backup:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GHCR_ACCESS_TOKEN }}
          submodules: recursive
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:
          port: 22
          script: |
            cd ~/anime-kr
            git pull
            cd infra-services
            ./deploy-backup-server.sh