name: deployment
on:
  pull_request:
    branches:
      - release
    types: [closed]
  push:
    branches:
      - main
jobs:
#  test:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: 21
#      - name: Test application
#        run: |
#          cd application-server
#          chmod +x gradlew
#          ./gradlew test
  build:
#    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ecsimsw
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
          logout: true
      - name: Build container image and push it to GHCR
        run: |
          cd application-server
          ./gradlew build -x test
          docker build -t ghcr.io/giggle-projects/anime-kr/latest .
          docker push
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:
          port: 2023
          script: |
            cd ~/dev/anime-kr
            git pull
            ./infra-services/deploy.sh
  deploy-backup:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase:
          port: 22
          script: |
            cd ~/anime-kr
            git pull
            ./infra-services/deploy-backup-server.sh