name: pr-validator
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world! dsafkldsafj
      - name: Get changed files
        run: |
          CHANGED_FILES=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
      - run: exit 1
